### ISSUE TITLE
DatePicker malfunction in  IE11

### ISSUE THREAD

**Issue by almli** [fremtind/jokul#568] opened 2019-12-09 15:41 UTC
**Describe the bug**
The date picker popup does not appear when the component gets focus. You must click on the checron to trigger the popup

In the extended version (extended=true) there is an addition problem with the styling. See attachment

**To Reproduce**
Just view the datepicker in IE11:  https://fremtind.github.io/jokul/components/datepicker/

**Expected behavior**
Should work as in Chrome

**Screenshots**

Standard version in IE11:
![IE11](https://user-images.githubusercontent.com/818715/70449610-8fee3a80-1aa2-11ea-8f4a-d0e38c568fb6.PNG)

Extended version in IE11:
![IE11-extended](https://user-images.githubusercontent.com/818715/70449622-941a5800-1aa2-11ea-8773-b4e58e22a614.PNG)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser IE11

**Comment by piofinn** [comment] 2019-12-10 09:24
Are you running a polyfill for custom elements? It looks like the `core-datepicker` component does not render at all (at least in the first case).

We'll start by looking at the bug in `NativeSelect`, as that has to be fixed in any case.

**Comment by almli** [comment] 2019-12-10 09:27
Yes. The datepicker pops up when I click on the chevron


tir. 10. des. 2019, 10:24 skrev Pio Rasch-Halvorsen <
notifications@github.com>:

**Comment by piofinn** [comment] 2019-12-10 09:28
Ah, yes I missed that. Will take a look!

**Comment by piofinn** [comment] 2019-12-10 10:07
The second issue will be fixed by #573.

We might end up changing the behaviour of the datepicker a little, so that you have to click a button to open it. This should fix the first issue, but We'll look into a quick fix in the mean time!

**Comment by SercanSercan** [comment] 2020-03-11 17:02
@piofinn 
I noticed that recommended polyfill (@webcomponents/custom-elements) is not installed on datepicker-react. (Ref: https://github.com/webcomponents/polyfills#custom-elements) And I am not able to verify whether the second problem was fixed or not because checkbox component fails in IE11. Do we already have a ticket for this?

**Comment by piofinn** [comment] 2020-03-11 21:43
> I noticed that recommended polyfill (@webcomponents/custom-elements) is not installed on datepicker-react.

The polyfill has to be provided by the project using the component, to avoid unecessary size in the packages. We should probably make sure it is run with the dev example, though! In this case, we can probably just use a CDN like unpkg if we want to keep devDependencies to a minimum 😊

**Comment by SercanSercan** [comment] 2020-03-31 13:43
The bug was caused by some _undefined_ initial value in Datepicker. I tested the solution on different browser in case of a regression (Firefox, Safari, Edge, IE11, etc). It is fixed and merged into master.

**Closed** 2020-03-31 13:43 UTC
Labels: 🐝 bug
